import enum


class OrderStatus(enum.Enum):

    COMPLETED = 'COMPLETED'
    PREPARING = 'PREPARING'
    PENDING_PICKUP = 'PENDING_PICKUP'
    PICKED_UP = 'PICKED_UP'
    CANCELLED = 'CANCELLED'
    DELIVERING = 'DELIVERING'
    PENDING_STORE = 'PENDING_STORE'
    PENDING_HELPER = 'PENDING_HELPER'


class OrderGroupStatus(enum.Enum):

    COMPLETED = 'COMPLETED'
    DELIVERING = 'DELIVERING'
    PENDING_PICKUP = 'PENDING_PICKUP'
    PENDING_HELPER = 'PENDING_HELPER'
